name: test

on: 
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [18, 20, 22, 24]
        
        services:
            mysql:
                image: mysql
                env:
                    MYSQL_DATABASE: test_auth
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
        
        container: node:${{ matrix.node }}
                    
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: check docker
              run: docker ps -a

            - name: nodejs version
              run: |
                node -v && cat index.js

            - name: install package
              run: |
                npm i && node index
