name: test on node 18, 20, 22, 24

on:
    push: 
        branches: 
            - master
    workflow_dispatch: 

jobs:
    mysql-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [18, 20, 22, 24]
        
        services:
            mysql:
                image: mysql
                env:
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_DATABASE: test_db
                ports:
                    - 3306:3306
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
            mongo:
                image: mongo
                env:
                    MONGO_INITDB_ROOT_USERNAME: mongo
                    MONGO_INITDB_ROOT_PASSWORD: password
                    MONGO_INITDB_DATABASE: mongo_db
                ports:
                    - 27017:27017
        
        container: node:${{ matrix.node }}

        steps:
            - name: checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: install mysql client
              run: |
                apt-get update
                apt-get install -y default-mysql-client
            
            - name: install postgres client
              run: |
                apt-get install -y postgresql-client
            
            - name: install mongodb shell
              run: |
                wget -qO - https://pgp.mongodb.com/server-6.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-6.0.gpg
                echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
                apt-get update && apt-get install -y mongo-tools
            
            - name: wait for database ready
              run: |
                until mysqladmin ping -h"mysql" -uroot -upassword --silent; do
                    echo "waiting for mysql"
                    sleep 2
                done

                until pg_isready -h "postgres" -p 5432 -U "postgres" > /dev/null 2>&1; do
                    echo "waiting for postgre"
                    sleep 2
                done

                until mongo --host "mongo" -u "mongo" -p "password" --authenticationDatabase admin --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
                    echo "waiting for mongodb"
                    sleep 2
                done
            
            - name: finish
              run: |
                echo "success"
              
